{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "e5d50fee-c47c-4b5b-8415-32de462734e5",
   "metadata": {},
   "source": [
    "(developer:exceptions)=\n",
    "# Exceptions"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "bdf76ad2-4899-40b9-b0bf-19c24e0ff98d",
   "metadata": {},
   "source": [
    "There is in the directory `pyunitwizard/_private_tools` a module named `exceptions.py` with customized exceptions. Use them timely. And, in case you want to raise a new exception type, please include it here for the others to use it.\n",
    "\n",
    "To use a exception you just need to import it and raise it:\n",
    "\n",
    "```python\n",
    "from pyunitwizard._private_tools.exceptions import NotImplementedMethodError\n",
    "\n",
    "def method_to_be_implemented_in_the_future():\n",
    "    \n",
    "    raise NotImplementedMethodError\n",
    "```\n",
    "\n",
    "Let's see the list of customized exceptions in pyunitwizard."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "76332749-e176-45d6-8de3-bd1ed184a6df",
   "metadata": {},
   "source": [
    "(developer:exceptions:NotImplementedMethodError)=\n",
    "## NotImplementedMethodError\n",
    "\n",
    "The `NotImplementedMethodError` exception is raised when a method has being already defined but its code was not fully implemented yet. Maybe the method was just included in a developing version to be coded in the future. Or maybe the method works already for certain values of the input arguments, but not for others yet.\n",
    "\n",
    "```{admonition} See also\n",
    ":class: attention\n",
    "{func}`pyunitwizard._private_tools.exceptions.NotImplementedMethodError`\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ea4551cc-18d2-468a-b869-9d20d64f9c9f",
   "metadata": {},
   "source": [
    "(developer:exceptions:NotImplementedClassError)=\n",
    "## NotImplementedClassError\n",
    "\n",
    "The `NotImplementedClassError` exception is raised when a class has being already defined but its code was not fully implemented yet. Maybe the class was just included in a developing version to be coded in the future. Or maybe the class can be instantated already for certain values of the input arguments, but not for others yet.\n",
    "\n",
    "```{admonition} See also\n",
    ":class: attention\n",
    "{func}`pyunitwizard._private_tools.exceptions.NotImplementedClassError`\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7b4ee5a4-13f4-4a4d-ba4e-6e670f82e750",
   "metadata": {},
   "source": [
    "(developer:exceptions:BadCallError)=\n",
    "## BadCallError\n",
    "\n",
    "The `BadCallError` is raised when a method was not properly called.\n",
    "\n",
    "This exception has an optional input argument: the name of the probable wrong input argument.\n",
    "\n",
    "```{admonition} See also\n",
    ":class: attention\n",
    "{func}`pyunitwizard._private_tools.exceptions.BadCallError`\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "50c5031d-1751-483c-909a-2135f38ab926",
   "metadata": {},
   "source": [
    "(developer:exceptions:NoStandardError)=\n",
    "## NoStandardError\n",
    "\n",
    "The `NoStandardError` is raised when a quantity needs to be standardized and there are not enough standards declared.\n",
    "\n",
    "```{admonition} See also\n",
    ":class: attention\n",
    "{func}`pyunitwizard._private_tools.exceptions.NoStandardError`\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "95e053cf-dcf6-480d-b833-de863010b572",
   "metadata": {},
   "source": [
    "(developer:exceptions:UnknownFormError)=\n",
    "## UnknownFormError\n",
    "\n",
    "The `UnknownFormError` is raised when the quantity has a form not recognized and supported by PyUnitWizard.\n",
    "\n",
    "```{admonition} See also\n",
    ":class: attention\n",
    "{func}`pyunitwizard._private_tools.exceptions.UnknownFormError`\n",
    "```"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "39fc5729-61ff-4714-8b18-1ac0d138e38d",
   "metadata": {},
   "source": [
    "(developer:exceptions:LibraryNotFoundError)=\n",
    "## LibraryNotFoundError\n",
    "\n",
    "The `LibraryNotFoundError` is raised when PyUnitWizard fails importing a library not required as dependence.\n",
    "\n",
    "This exception has a mandatory input argument: the name of library not found.\n",
    "\n",
    "```{admonition} See also\n",
    ":class: attention\n",
    "{func}`pyunitwizard._private_tools.exceptions.LibraryNotFoundError`\n",
    "```"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
